### ISSUE TITLE
Add portability with Linux

### ISSUE THREAD

**Issue by Nircek** [Nircek/resistorer#2]

**Comment by Nircek** [comment]
Win10 output:
```
<KeyPress event keysym=F1 keycode=112 x=99 y=199>
<KeyPress event keysym=F1 keycode=112 x=131 y=228>
<KeyPress event keysym=F1 keycode=112 x=136 y=241>
<KeyPress event keysym=F1 keycode=112 x=163 y=225>
<KeyPress event keysym=F1 keycode=112 x=133 y=202>
<KeyPress event keysym=F1 keycode=112 x=176 y=240>
<KeyPress event keysym=F3 keycode=114 x=80 y=200>
<KeyPress event keysym=F4 keycode=115 x=198 y=237>
<KeyPress event keysym=slash keycode=191 char='/' x=140 y=226>
pos(2, 5) -pos(2, 5, 0)-> pos(3, 5) -pos(3, 5, 0)-> pos(4, 5) -pos(4, 5, 1)-> pos(4, 6) -pos(4, 6, 0)-> pos(5, 6) -pos(2, 5, 0)-> pos(3, 5) -pos(3, 5, 1)-> pos(3, 6) -pos(3, 6, 0)-> pos(4, 6) -pos(4, 6, 0)-> pos(5, 6)
<KeyPress event keysym=Shift_L keycode=16 x=140 y=226>
<KeyPress event state=Shift keysym=plus keycode=187 char='+' x=140 y=226>
<KeyPress event keysym=Shift_L keycode=16 x=140 y=226>
<KeyPress event state=Shift keysym=plus keycode=187 char='+' x=140 y=226>
<KeyPress event state=Shift keysym=plus keycode=187 char='+' x=140 y=226>
<KeyPress event keysym=equal keycode=187 char='=' x=140 y=226>
<KeyPress event keysym=equal keycode=187 char='=' x=140 y=226>
<KeyPress event keysym=equal keycode=187 char='=' x=140 y=226>
<KeyPress event keysym=equal keycode=187 char='=' x=140 y=226>
<KeyPress event keysym=equal keycode=187 char='=' x=140 y=226>
<KeyPress event keysym=Shift_L keycode=16 x=140 y=226>
<KeyPress event state=Shift keysym=plus keycode=187 char='+' x=140 y=226>
<KeyPress event keysym=equal keycode=187 char='=' x=140 y=226>
<KeyPress event keysym=Shift_L keycode=16 x=140 y=226>
<KeyPress event state=Shift keysym=plus keycode=187 char='+' x=140 y=226>
<KeyPress event state=Shift keysym=plus keycode=187 char='+' x=140 y=226>
<KeyPress event state=Shift keysym=plus keycode=187 char='+' x=140 y=226>
<KeyPress event keysym=minus keycode=189 char='-' x=140 y=226>
<KeyPress event keysym=minus keycode=189 char='-' x=140 y=226>
<KeyPress event keysym=minus keycode=189 char='-' x=140 y=226>
<KeyPress event keysym=minus keycode=189 char='-' x=140 y=226>
<KeyPress event keysym=Shift_L keycode=16 x=140 y=226>
<KeyPress event state=Shift keysym=underscore keycode=189 char='_' x=140 y=226>
<KeyPress event state=Shift keysym=underscore keycode=189 char='_' x=140 y=226>
<KeyPress event state=Shift keysym=underscore keycode=189 char='_' x=140 y=226>
<KeyPress event state=0x40000 keysym=Delete keycode=46 x=151 y=230>
<KeyPress event state=0x40000 keysym=Delete keycode=46 x=183 y=251>
<KeyPress event keysym=Shift_L keycode=16 x=183 y=251>
<KeyPress event state=Shift|0x40000 keysym=Delete keycode=46 x=183 y=251>
<KeyPress event keysym=backslash keycode=220 char='\\' x=-117 y=214>
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> ^Z

now exiting InteractiveConsole...
Traceback (most recent call last):
  File "C:\Users\mzepp\GH\resistorer\main.py", line 344, in <module>
    board.render()
  File "C:\Users\mzepp\GH\resistorer\main.py", line 208, in render
    self.w.delete('all')
  File "C:\Users\mzepp\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 2511, in delete
    self.tk.call((self._w, 'delete') + args)
_tkinter.TclError: invalid command name ".!canvas"
```

**Comment by Nircek** [comment]
Arch Linux output:
```
<KeyPress event keysym=F1 keycode=67 x=124 y=108>
<KeyPress event keysym=F2 keycode=68 x=124 y=108>
<KeyPress event keysym=F3 keycode=69 x=124 y=108>
<KeyPress event keysym=F4 keycode=70 x=124 y=108>
<KeyPress event keysym=slash keycode=61 char='/' x=124 y=108>
<KeyPress event keysym=equal keycode=21 char='=' x=124 y=108>
<KeyPress event keysym=Shift_L keycode=50 x=124 y=108>
<KeyPress event state=Shift keysym=plus keycode=21 char='+' x=124 y=108>
<KeyPress event keysym=minus keycode=20 char='-' x=124 y=108>
<KeyPress event keysym=Shift_L keycode=50 x=124 y=108>
<KeyPress event state=Shift keysym=underscore keycode=20 char='_' x=124 y=108>
<KeyPress event keysym=Delete keycode=119 char='\x7f' x=124 y=108>
NO F8 ELEMENT
<KeyPress event keysym=Delete keycode=119 char='\x7f' x=124 y=108>
NO F8 ELEMENT
<KeyPress event keysym=Shift_L keycode=50 x=124 y=108>
<KeyPress event state=Shift keysym=Delete keycode=119 char='\x7f' x=124 y=108>
NO F8 ELEMENT
<KeyPress event keysym=backslash keycode=51 char='\\' x=124 y=108>
<KeyPress event keysym=Alt_L keycode=64 x=234 y=-10>
Traceback (most recent call last):
  File "./main.py", line 344, in <module>
    board.render()
  File "./main.py", line 208, in render
    self.w.delete('all')
  File "/usr/lib/python3.7/tkinter/__init__.py", line 2514, in delete
    self.tk.call((self._w, 'delete') + args)
_tkinter.TclError: invalid command name ".!canvas"
```

**Comment by Nircek** [comment]
Therefore, it can be concluded that using keycodes to handle chars is not portable

**Comment by Nircek** [comment]
https://github.com/Nircek/resistorer/blob/ec8188b8eb7398317ded2b00a68ee056510596e8/main.py#L315
On Win10 it's 'quoteright'.

**Comment by Nircek** [comment]
Repaired in 62ae36e39036c0d203a25ad9b5f71cd24252151d.
